version: '3.8'

services:
  web:
    container_name: web_app
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: