version: '3.8'

services:
  web:
    container_name: web_app
    build: .
    env_file:
      - .env 
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: