"""recovery password

Revision ID: 1e706e7d8928
Revises: bca2f7ec3833
Create Date: 2025-03-08 16:41:46.906348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e706e7d8928'
down_revision = 'bca2f7ec3833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_recovery_password', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_recovery_password')

    # ### end Alembic commands ###
