"""User now hase KeyChain ID as foreign key

Revision ID: 64ea3db6edcd
Revises: 8218c8d133bb
Create Date: 2025-02-25 21:46:19.225002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ea3db6edcd'
down_revision = '8218c8d133bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('key_chain', schema=None) as batch_op:
        batch_op.drop_constraint('key_chain_user_id_key', type_='unique')
        batch_op.drop_constraint('key_chain_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keychain_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['keychain_id'])
        batch_op.create_foreign_key(None, 'key_chain', ['keychain_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('keychain_id')

    with op.batch_alter_table('key_chain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('key_chain_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_unique_constraint('key_chain_user_id_key', ['user_id'])

    # ### end Alembic commands ###
