"""Added created_at timestamp to OneTimePassword

Revision ID: 8218c8d133bb
Revises: 50034f19d4af
Create Date: 2025-01-27 23:39:30.905600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8218c8d133bb'
down_revision = '50034f19d4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('one_time_password', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
