"""Changed entry name to not unique

Revision ID: 92f8b8216c40
Revises: e1eedb884f9d
Create Date: 2024-10-21 18:12:38.025409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f8b8216c40'
down_revision = 'e1eedb884f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.drop_constraint('vault_entry_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.create_unique_constraint('vault_entry_name_key', ['name'])

    # ### end Alembic commands ###
