"""initial migration

Revision ID: 9c772aef6556
Revises: 
Create Date: 2025-03-08 15:41:04.604573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c772aef6556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_totp_derived_key', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('totp_salt', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_salt')
        batch_op.drop_column('encrypted_totp_derived_key')

    # ### end Alembic commands ###
